// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCACLPAwmqTHtzmMQ05K1JA1BkL9VMngqg',
    appId: '1:763480870514:web:dc0e4b17886f4d0ab1bceb',
    messagingSenderId: '763480870514',
    projectId: 'nessbid-1',
    authDomain: 'nessbid-1.firebaseapp.com',
    storageBucket: 'nessbid-1.firebasestorage.app',
    measurementId: 'G-NS14KP5KYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCACLPAwmqTHtzmMQ05K1JA1BkL9VMngqg',
    appId: '1:763480870514:android:a1b2c3d4e5f6a7b8',
    messagingSenderId: '763480870514',
    projectId: 'nessbid-1',
    storageBucket: 'nessbid-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCACLPAwmqTHtzmMQ05K1JA1BkL9VMngqg',
    appId: '1:763480870514:ios:dc0e4b17886f4d0ab1bceb',
    messagingSenderId: '763480870514',
    projectId: 'nessbid-1',
    storageBucket: 'nessbid-1.firebasestorage.app',
    iosBundleId: 'com.financeapp.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCACLPAwmqTHtzmMQ05K1JA1BkL9VMngqg',
    appId: '1:763480870514:ios:dc0e4b17886f4d0ab1bceb',
    messagingSenderId: '763480870514',
    projectId: 'nessbid-1',
    storageBucket: 'nessbid-1.firebasestorage.app',
    iosBundleId: 'com.financeapp.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCACLPAwmqTHtzmMQ05K1JA1BkL9VMngqg',
    appId: '1:763480870514:web:dc0e4b17886f4d0ab1bceb',
    messagingSenderId: '763480870514',
    projectId: 'nessbid-1',
    authDomain: 'nessbid-1.firebaseapp.com',
    storageBucket: 'nessbid-1.firebasestorage.app',
    measurementId: 'G-NS14KP5KYV',
  );
}
